### ISSUE TITLE
Some observations of the admin of Ladybug Tools

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#15]
@ladybug-tools/core 

###  Communications
Always a good thing to add the team a message is addressed to at the top of an issue.  This message is addressed to: @ladybug-tools/core. Of course, if a product is truly open then all messages are open to all, but addressing to particular teams helps peeps filter what they have to read.

I would be pleased to see a page that describes how we should communicate along with guidelines and standards we would like to follow,

### Naming Strategy   
Currently I see much that is unclear about the way peeps use the word 'Ladybug'. Is it a company? Is it a way of organizing things. Is it a product? Yes, I know, it's all of the above. But this causes issues. For example most people used to think I worked for a company called 'AutoCAD'.

Has there been a discussion about product naming strategy? Is there any documentation anywhere on naming strategy and ways of clarifying things to end users?

### Web Site Audience
It is unclear to me who the target purpose is for the proposed web site. The current look and feel of the site makes me think of a calling card site. Something that is like an online business card. People go to these sites once or twice, get what they need and rarely return.

Sites that have significant return visitors must have fresh content - at least every few days - on the home page with details to more in depth updates a click away.

Also, the target audience - with all the stunning graphics - seems target towards designers and firms of engineers. Yet when I look at the repos on GitHub what I see are docs for Python code - material targeted for coders

### Web Site Maintenance
A very large factor in the success of a web site is the amount of time and effort it takes to update the site. The more clicks required to update the site the sooner the site will die. 

Example: Medium is taking over from WordPress because you can just join and start writing. No need to set themes or upload images.

My dream is a web site based on new issues, commit messages and easy to update Markdown files. You just commit and discuss and somehow the web site technology watches what you are doing on GitHub and freshens its content accordingly.

### Writing for Strangers
Much of the knowledge currently being cataloged in the read me and web pages presupposes that you already know what is going on. You must already be familiar with terms such as such as 'Grasshopper;, 'LEED', 'OpenFOAM, 'OpenStudio' and many, many others.

Writing like this is OK for 'friends of the family' but is a nearly instant way of getting most peeps to leave the site.

Any technical term such as [visual programing language]( https://en.wikipedia.org/wiki/Visual_programming_language ) or [Dynamo]( https://www.autodesk.com/products/dynamo-studio/overview ) should have a link to a Wikipedia or a product page.

Think of the web pages you create. The internal links between the pages are like doors connecting the rooms. But the links to pages outside are like windows giving on to the world.

***

I can write on all of the above in more much more detail. And I can probably add a bunch more topics. and - more importantly - I can actually draft full responses and guidelines to all of these topics.

But it will only be worth doing if there is agreement that these sorts of matters are relevant to the project. This means that some peep(s) will have to take charge and start managing the various efforts.

The interesting thing is that the problem of managing complex issues has very much been simplified by GitHub. People like Mike Bostock and Mr.doob manage huge complex projects - simply by maintaining and merging pull requests.

Anyway, I look forward to reading your comments and suggestions regarding how I can best be an asset to this project.

Theo

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour. Valuable points as usual. Here are my comments.

> I would be pleased to see a page that describes how we should communicate along with guidelines and standards we would like to follow,

Yes please! I need to add one for the development for contributing code to ladybug tools and how we develop. Some [version of this guideline](https://github.com/Khan/style-guides/blob/master/style/python.md). The wiki on GitHub should be a great place to get this started. If can get this started we will follow your lead. 

### Naming Strategy

This is (and will be) a problem and is not well documented yet. Where do you think we should put this? In [about page](http://www.ladybug.tools/eval/about.html)?

The short answer is that Ladybug Tools LLC is a company, Ladybug Tools is a collection of tools which are currently Ladybug, Honeybee, Butterfly and Dragonfly.

### Website

Website (ladybug.tools) is currently mainly for non-developers and GitHub organization (www.github.com/ladybug-tools) is for developers.

I think except for the discussion forum and probably a news segment most of the pages will stay static and won't change as much. We have done websites like [Hydra](http://hydrashare.github.io/hydra/) that are generated based on data on GitHub pages but I'm not sure our website is going to be updated as much. Most of the new stuff will happen in the discussion forum or GitHub and the ones that needs to be shared will be pushed to twitter and/or Facebook. For API documentation and such we have already automated the process.

If I want to use your own analogy I think of the forum as the coffee shop / bar where people go to hangout and the rest of the pages are like administrative offices that you don't go unless you really need to!

 It might be a good idea to have a separate page for developers on the website which will be collection of links to Github pages with short description of each so we don't have to update them both on Github and the ladybug.tools

### Maintenance

Assuming that we won't update the page as frequently the current method, which is editing the HTML, should be fine. If we decide to have blog posts then using medium with ladybug_tools handle is the way to go. The strategy is to use the best available. I like to hear what other people think. I'm personally against of using content managers but I know not using them will only works for developers which is who we are so it should be fine.

###  Writing for Strangers

You're right and I'm mostly to blame. More than not wanting to provide links is that since we use these terms on a daily basis it's hard for us to see which parts are needed to be linked. @theo-armour you can help us a lot here by pointing out which are the terms that need a link. We will take it from there.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Thank you for the many replies.

### Using the GitHub Wiki. 
From what I can see, most Wikis on GitHub have not been particularly successful. There could be a number of reasons for this. Some of these might be that a Wiki does not go through the normal pull request, merge and commit process. Thus extra/different work is added and that makes life more complicated for the maintainer. Most quality docs on GitHub seem to be maintained via the normal GitHub commit process. I can go into much more detail and post links of examples if needed, but my initial reaction is to avoid using the GitHub Wiki for anything where you want a good collaboration and good revision control

### All the other points
Each could (and eventually must ) have their own separate issue threads. If this is truly an open organization, then topics like these should be written about and viewable by the public

### Over-arching thing
What are the two or three things you would like me to be doing in the next week or so?

I will soon be starting solar calcs on 3D terrain and updating all the viewers, but apart from that what are the  admin type of things you think I should be working on?

**Comment by mostaphaRoudsari** [comment]
@theo-armour thank you for the reply and sorry for the delayed response.

### Using the GitHub Wiki.

I love you hear more about your suggestions. What do you think about using gitbooks? It is based on github repositories and you can use commits, pull requests, etc. Here is the [gitbook for butterfly](https://ladybug-tools.gitbooks.io/butterfly-primer/content/) and [the repository](https://github.com/ladybug-tools/butterfly-primer).

### All the other points

@theo-armour let's set up a call and talk about both. We will add the results of the call to this issue. It will be much easier to discuss the initial steps and then we can use issues to make them happen.

### Over-arching thing

This can also be part of the call but for now I think one development that can be very useful and change the sunpath from a visualization tool to an analysis tool is adding [solar access](https://en.wikipedia.org/wiki/Solar_access) analysis to the analemma tool. To do so you need to count the number of suns that are visible to each geometry face. We already have the sun vectors, what needs to be done is:

1. Break down each face to smaller faces so we have a higher resolution analysis.
2. Shoot a vector from the center of each face for each sun and calculate the intersection.
3. Count the number of sun vectors that doesn't intersect with the geometries (this is the solar access value).
4. Color the mesh faces based on solar access.

**Comment by mostaphaRoudsari** [comment]
@theo-armour I tried to address the issue with external links. Let me know if there is more that I need to add.

**Comment by theo-armour** [comment]
>  What do you think about using gitbooks?

I really like GitBooks. That's why I built this thing

https://pushme-pullyou.github.io/tootoo/r5/ladybug-tools-view/ladybug-tools-view-r1.html#tootoo/r5/ladybug-tools-view/README.md

I wanted to do what GitBooks is doing just using the GitHub pages feature and without having to build or compile or whatever. And there's a bunch more stuff. GitBooks takes you to Facebook/Weibo. No thank you. I want to go to the source code on GitHub and commit a change. I want to show 3D models and example files. And so on. And all in kindergarten JavaScript, please.

> let's set up a call and talk about both. 

Good idea. Wednesday I'm out between 2-5 pm PST but otherwise available - but usually not functioning until after 11 am ;-)

> Solar access

Can do. Do you have a suitable 3D model for this?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

RE: Solar Access

Is there a standard for the shades or colors used to indicate the solar access for a particular face?

Are the following assumptions correct:

* Looking to calculate the position of the Sun from dawn to sunset from ten ( or more ) equally spaced positions
* The default should be at December 21st in the Northern Hemisphere and June 21 in the Southern. The user may select any other date.
The intensity of the Sun is assumed to be equal at all points. No allowance is needed for atmosphere
