### ISSUE TITLE
Publications list

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools.github.io#17]
@ladybug-tools/core, @ladybug-tools/collaborators, @ladybug-tools/honeybee-core-developers 

What are the publications that we need to add to the [publication page](http://www.ladybug.tools/eval/publication)?

Generally speaking what is the criteria to include a publication on publications page? I mainly included the papers that are discussing the core development of Ladybug Tools.

Also should we include presentations like [this one](https://www.radiance-online.org/community/workshops/2016-padua/presentations/213-SadeghipourSubramaniam-AutomatingWorkflows.pdf) for Radiance Workshop on the page?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Good start.

Here is the link for the criteria Wikipedia uses for references. You will note that the link is on the ISBN number. https://en.wikipedia.org/wiki/Wikipedia:Scientific_citation_guidelines

I note that references in journals are usually left-justified. Currently the text is centered - and in my opinion looks pretty more than looking professional.

I will have a look at editing the text and making a pull request. I may also add the abstracts under the references.

***

Regarding what to post, It could be anything 'published' in any media - book, mag, blog post whatever.

Slide shows and presentations are good too, but these might better be included in support/help/documentation pages.

https://github.com/ladybug-tools/ladybug-tools.github.io/blob/master/eval/support.md

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

Another one of the Building simulation papers that I am an author on is heavily reliant on Ladybug and features a lot of Ladybug graphics.  I think we can include this one.

I also know that there are a lot of academic journal papers using Ladybug that people have posted to the GH group forum.  I think these should go up there and, if you agree, I can track them down.

Finally, it may be worth linking to my thesis for 2014 since this is still probably the best documentation of the microclimate maps:
https://dspace.mit.edu/handle/1721.1/99261

-Chris

**Comment by chriswmackey** [comment]
Ah, I did not mean to close this issue. That was an accident.

**Comment by mostaphaRoudsari** [comment]
@theo-armour noted! I'll change the style. I will try a couple of options including double columns. 

@chriswmackey can you share the info about the paper that you mentioned?

I actually copied the link to your thesis but I should have forgotten to put it in! :|

and yes, let's add the ones from the forum. I think we shared most of them also on the Facebook and twitter which should be a better place to try to find them.
