### ISSUE TITLE
Error in PMVCalculator

### ISSUE THREAD

**Issue by ocni-dtu** [ladybug-tools/ladybug-tools.github.io#23]
Get a error when I try to use the PMVComfortCalculator with the following values:
Ta = 35°C
RH = 50% 
MRT < -28.32°C
MET = 2.3
Clo = 0.46

Everything with a MRT below -28.32°C gives an error. I know that seems like an unusual setup with Ta = 35°C and MRT -28°C. But I find it strange that there comes a error right at -28.32°C.
I have added a gh file with the setup.
[Comfort_Error.zip](https://github.com/ladybug-tools/ladybug-tools.github.io/files/1290583/Comfort_Error.zip)

**Comment by chriswmackey** [comment]
@ocni-dtu ,

It seems that you have found a condition where the human body cannot easily reach an equilibrium and this is causing the "while" loop within the PMV model to diverge. You will see that there's nothing special about -28.32 and the error has more to do with the difference between air temperature and radiant temperature.  Just drop the air temperature down a few degrees and things will work.

It probably goes without saying that a 50C difference between radiant and air temperatures is a set of conditions that the PMV model really isn't meant to handle.  We already know that the PMV model really doesn't do a such a good job with conditions that are far from typical indoor air conditioned ones so I wouldn't trust these results too much for this situation.  I would guess that the outdoor comfort models like UTCI or PET might be better equipped to handle such odd situations because outdoor temperatures are more extreme.

I can add a warning that the PMV model isn't fit to handle these conditions into the Ladybug component but such a line of when the model isn't fit is a fuzzy, subjective one.  If we want to draw a line at 50C, though, that sounds good to me.

Also, this repository is not the right place to post issues about the Legacy version of Ladybug.  As a result, I am closing this issue and please post any future issues here instead:
https://github.com/mostaphaRoudsari/ladybug/issues

-Chris
