### ISSUE TITLE
Update bios

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools.github.io#38]
👋 @stgeorges, @AntonelloDN, @TheodoreGalanos, @Vyrwn, @mdengusiak, @AntoineDao, @MingboPeng, @saeranv, @devngc!

It looks like all of your bios needs to be updated. Interesting how almost everyone has changed their jobs. 😀

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari ,
I am fine with the current biography info :)

**Comment by Vyrwn** [comment]
Hi Mostapha,

thanks for still including me in the team.
here is my updated bio.

-----
Byron is a Creative Technology Associate at Bryden Wood
<https://www.brydenwood.co.uk/> in London. He tries to develop new tools
and platforms in order to improve workflow in-house but also in open source
projects. He previously worked as an Associate Environmental Engineer at
Foster + Partners, integrating the environmental thinking during the
design process with the use of parametric and dynamic technologies. He also
teaches computational methods in the Sustainable Environmental Design
master's programme in Architectural Association school of Architecture in
London. His contribution to Ladybug tools relate to solar assessment and
daylight simulation.
-----

it's actually a bit funny because I have only been in the new place for 3
weeks, so my role is a bit vague at the moment. I was also put in charge of
a completely non-related project until the end of the month, so I will
start doing environmental integration and form my role some point in the
summer. In any case I will let you know if there is anything not accurate
in my bio in a couple of months.

kind regards,
Byron

**Comment by saeranv** [comment]
Nice, didn't realize you left Foster @Vyrwn. Congratulations on your new job!

**Comment by Vyrwn** [comment]
It is very fresh. Only 3 weeks out of Fosters and into the new place. Thank you @saeranv . It definitely looks interesting, I hope something nice will come out of it.

**Comment by michaldengusiak** [comment]
ok my is updated and [PR raised](https://github.com/ladybug-tools/ladybug-tools.github.io/pull/40),
