### ISSUE TITLE
friends and foes

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-tools.github.io#8]
@ladybug-tools/owners 

Would it be possible to come up with a list of three or more web sites that are in the same field as we are and that we feel are doing a reasonable job of explaining who they are to new users as well as being useful to existing users?

We want to be able to show the same kind of information about us as they do about themselves. And we can try to do even better!

If we are going to have a good site, then we should be able to compare and contrast with the best in the field.

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour,

[Processing](https://processing.org/) is a good reference. Their website is a little bit old but they are very similar in case of what they do.

[d3.js](https://d3js.org/) is another one with the difference that it's a website mainly designed for developers.

I also think users will give us feedback about the website as we go so we will know more what they will be looking for on the website. Right now I feel documentation is missing and also we may want to have a direct link to examples on Hydra from the main page but again I think that's something that the users will tell us once the website is live.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Very interesting choices. And not at all what I anticipated.

My thought was that you would e considering various web sites concerned with heating, energy, light and similar engineering calculations. Instead you went in the direction of programming, language and graphics.

My first thought is this means I am not well informed regarding your intentions. and could use some help in understanding things. So do you have a business plan or over-arching documents on what your plans are for Ladybug Tools?

y second thought is that we should be looking at various engineering sites and comparing and contrasting their benefits and features.

Finding sites and looking at them is actually a quite labor intensive task. Comparing sites is even more time-consuming. Recently I have been thinking about and experimenting with building dashboards, browsing tools and the such.

Today's effort grabs all the sponsor's links from http://www.buildingsimulation2017.org/ and puts them in  Windows Explorer style interface where you can click and view, click and view.

## [Links to Sponsors - Building Simulation 2017]( http://rawgit.com/ladybug-tools/ladybug-web/gh-pages/utilities/sponsor-links-bs2017/sponsor-links-bs2017-r1.html )

The links are gathered by the program client-side at run-time. The BS2017 has some scraping protection so I used the Yahoo Query Language tool to snatch the source for the script. I plan to build more tools like this and will be looking for web pages with lots of nice things to browse. [Maybe this might be good: http://www.food4rhino.com/ ].

Anyway, you now have a way of checking out over 30 sites involved with building simulation.

In any case, while we are designing and detailing the site it might be a good thing to to decide who the site is for, what we want to show them and how best to do this.

I think that GitHub issues is a good place for this sort of discussion - especially when people are conscious of staying on topic and seeking to close issues.

Not yet finished...

**Comment by mostaphaRoudsari** [comment]
@theo-armour, 

> My first thought is this means I am not well informed regarding your intentions. and could use some help in understanding things. So do you have a business plan or over-arching documents on what your plans are for Ladybug Tools?

We do. We have been modifying it for some time now and we're getting closer to a final decision. I can share the google docs with you with more details if you're interested. The reason I pointed out processing and d3 rather than [DesignBuilder](https://www.designbuilder.co.uk/) or [IES](https://www.iesve.com/) is because I see us much more similar to the first group. We're first trying to develop an integrated platform (core libraries) which can also be used to create applications and plugins. We're not creating a stand-alone simulation suite to limit people to our development and also give more access to whomever pays more.

We're thinking that we can make money via 4 channels which none of the them is the software itself.

1. Teachings and workshops: The income is just fine. It's quite time-consuming and it doesn't scale well. In the long run, we prefer to educate other advanced users to take on the workshops so we can concentrate on the development.

2. Consultancy: This is similar to teaching. It's very helpful to keep us in the loop and optimize the development for the practice. This has been the case so far and has been very helpful but again at some point it can be distraction for the development unless it is a development related consultancy.

3. Contributions: We have a large enough community to hope this can work but this is again something that we haven't really tested yet. The initial hope was to be able to start a non-profit organization and attract donations from offices and software companies but it doesn't seem to be the easiest option to establish in the US. You can [read more here](https://dash.harvard.edu/bitstream/handle/1/30805146/2017-03-24_governance.pdf). We have to go with an LLC. I think we can still attract some contribution from major companies who are using Ladybug Tools and their day to day work depends on our work plus Autodesk and McNeel, or any other software that we develop a plugin for them later. Is it going to be enough to make our development sustainable? We hope but we won't know until we get it started.

4. Cloud service: This is the one that I think is the most stable and meaningful way for us to stabilize the development. Specially for multi-phase daylight and CFD analysis we need to set up a cloud service. There are cloud services out there for generic use but they are not optimized for our workflows. We tried to team-up with already established cloud services but we don't have a final solution yet. I'm mostly to blame as I didn't dedicate enough time to this item but I have it on top of my list after release of honeybee[+] and initial documentation for developers.

> second thought is that we should be looking at various engineering sites and comparing and contrasting their benefits and features.

Thank you for creating the parser. I can provide you a list of the companies who are developing simulation software. Most of them are stand-a-lone proprietary software and tailored towards simulation experts more than designers and engineers. I personally don't think that we're going to replace them. Maybe one uses Honeybee and [OpenStudio](https://www.openstudio.net/) instead of DesignBuilder but then that's Honeybee and OpenStudio and not Honeybee itself. In other words we're not competing against them. We are providing an open, customizable and integrated alternative. Our website just need to make clear what we do and why we do it! Our successful work out there is our marketing material.

We can move the conversation to ladybug slack channel if necessary but I thought it's good to have it also documented here so everyone can see it and comment.

PS- [As it may come up and other people have already suggested it] We intentionally don't want to go the start-up route. I have my own reasons for that and have discussed them by @chriswmackey but that's a different discussion.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

>  I can share the google docs with you with more details if you're interested.

Please do share. I will be delighted to reads and comment.

After reading it I will be more knowledgeable about your comments here. Anyway, so far it's good and I agree and follow your thinking.

> We can move the conversation to ladybug slack channel if necessary but I thought it's good to have it also documented here so everyone can see it and comment.

If a project is truly open source then it's decision making process is open as well. I feel that projects like Three.js and Linux are successful because anybody go access all the messages that lead up to the various edits and updates.

> We intentionally don't want to go the start-up route.

Bootstrapping is good.
